class DropdownOptions {
  static List<String> conditionOptions = [
    'Neu, mit Etikett',
    'Neu',
    'Sehr gut',
    'Gut',
    'Zufriedenstellend'
  ];

  static List<String> typeOptions = ['Kids', 'Adults', 'Universal'];

  static Map<String, List<String>> sizeOptionsCloth = {
    'Adults': ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', 'Einheitsgröße'],
    'Kids': [
      '128',
      '134',
      '140',
      '146',
      '152',
      '158',
      '164',
      '170',
      '176',
      'Einheitsgröße'
    ],
    'Universal': ['Einheitsgröße'],
  };

  static Map<String, List<String>> sizeOptionsShoe = {
    'Adults': [
      'EU 36',
      'EU 36 2/3',
      'EU 37 1/3',
      'EU 38',
      'EU 38 2/3',
      'EU 39 1/3',
      'EU 40',
      'EU 40 2/3',
      'EU 41 1/3',
      'EU 42',
      'EU 42 2/3',
      'EU 43 1/3',
      'EU 44',
      'EU 44 2/3',
      'EU 45 1/3',
      'EU 46',
      'EU 46 2/3',
      'EU 47 1/3',
      'EU 48',
      'EU 48 2/3',
      'Einheitsgröße'
    ],
    'Kids': [
      'EU 28',
      'EU 28 1/2',
      'EU 29',
      'EU 30',
      'EU 30 1/2',
      'EU 31',
      'EU 31 1/2',
      'EU 32',
      'EU 33',
      'EU 33 1/2',
      'EU 34',
      'EU 35',
      'EU 35 1/2',
      'EU 36',
      'EU 36 2/3',
      'EU 37 1/3',
      'EU 38',
      'EU 38 2/3',
      'Einheitsgröße'
    ],
    'Universal': ['Einheitsgröße'],
  };

  static List<String> popularBrandOptions = ['Adidas', 'Puma', 'Nike'];
  static List<String> lessPopularBrandOptions = [
    'Keine Auswahl',
    'Asics',
    'Brooks',
    'Capelli',
    'Castore',
    'Columbia',
    'Converse',
    'Craft',
    'Diadora',
    'Fila',
    'Hummel',
    'Jako',
    'Joma',
    'Kappa',
    'K-Swiss',
    'Macron',
    'Merrell',
    'Mizuno',
    'New Balance',
    'Oakley',
    'Reebok',
    'Saller',
    'Salomon',
    'Skechers',
    'The North Face',
    'Uhlsport',
    'Umbro',
    'Under Armour',
    'Wilson'
  ];

  static List<String> clubOptions = [
    'Keine Auswahl',
    '1. FC Fuchsstadt',
    '1.FC Passau',
    'ASV Cham',
    'ASV Neumarkt',
    'ATSV Erlangen',
    'Baiersdorfer SV',
    'DFI Bad Aibling',
    'DJK Don Bosco Bamberg',
    'DJK Ingolstadt',
    'DJK Vilzing',
    'ESV Freilassing',
    'FC 1920 Gundelfingen U19',
    'FC Alkofen',
    'FC Coburg',
    'FC Deisenhofen',
    'FC Dingolfing',
    'FC Eintracht Bamberg',
    'FC Ergolding',
    'FC Ismaning',
    'FC Kempten',
    'FC Künzing',
    'FC Lauingen U19',
    'FC Memmingen',
    'FC Schwabing',
    'FC Schweinfurt 05',
    'FC Sonthofen',
    'FC Stätzling',
    'FC Stätzling',
    'FC Velden-Eberspoint',
    'FC Weiden-Ost',
    'FC Würzburger Kickers',
    'FSV Bayreuth',
    'FSV Erlangen-Bruck',
    'FT Schweinfurt',
    'FV Illertissen',
    'Heiligenstadt',
    'Jahn Regensburg Futsal',
    'JFG 3 Schlösser-Eck',
    'JFG Befreiungshalle Kelheim',
    'JFG Bibertgrund',
    'JFG Deichselbach-Regnitzau',
    'JFG Donautal Bad Abbach',
    'JFG FC Stiftland',
    'JFG GW Frankenwald',
    'JFG Kickers Bachgau',
    'JFG Kinsachkickers',
    'JFG Kreis Würzburg Süd-West',
    'JFG Lamer Winkel',
    'JFG Leitenbachtal',
    'JFG Lichtenfels-Leuchsental',
    'JFG Naab-Regen',
    'JFG Oberes Egertal',
    'JFG Rödental Coburger Land',
    'JFG Steigerwald',
    'JFG Tangrintel',
    'JFG Vorspessart',
    'JFG Wendelstein',
    'JSG Dreiländereck',
    'Post SV Nürnberg',
    'SB Chiemgau Traunstein',
    'SC E. Freising',
    'SC Landshut-Berg',
    'SC Regensburg',
    'SC Unterpfaffenhofen',
    'SG Quelle',
    'SGV Nürnberg-Fürth',
    'SpVgg Ansbach',
    'SpVgg Bayern Hof',
    'SpVgg Bayreuth',
    'SpVgg GW Deggendorf',
    'SpVgg Hösbach-Bahnhof',
    'SpVgg Kaufbeuren',
    'SpVgg Landshut',
    'SpVgg Mögeldorf',
    'SpVgg Ruhmannsfelden',
    'SpVgg SV Weiden',
    'SpVgg Unterhaching',
    'SSV Eggenfelden',
    'SSV Jahn Regensburg',
    'SV Alemannia Haibach',
    'SV Aubing',
    'SV Etzenricht',
    'SV Heidingsfeld',
    'SV Heimstetten',
    'SV Kürnach',
    'SV Manching',
    'SV Planegg-Krailling',
    'SV Raigering',
    'SV Schalding-Heining',
    'SV Schwandorf-Ettmannsdorf',
    'SV Türkgücü München',
    'SV Unterreichenbach',
    'SV Waldeck-Obermenzing',
    'Tirschenreuth',
    'TSG 08 Roth',
    'TSV 1860 Rosenheim',
    'TSV 1860 Weißenburg',
    'TSV 1861 Nördlingen',
    'TSV 1863 Krumbach',
    'TSV 1865 Dachau',
    'TSV 1865 Murnau',
    'TSV 1874 Kottern',
    'TSV 1888/1920 Regen',
    'TSV 1896 Rain',
    'TSV 1909 Gersthofen',
    'TSV Aubstadt',
    'TSV Ebermannstadt',
    'TSV Essleben',
    'TSV Großbardorf',
    'TSV Haunstetten',
    'TSV Kareth-Lappersdorf',
    'TSV Kümmersbruck',
    'TSV Neuried',
    'TSV Rückersdorf',
    'TSV Schwaben Augsburg',
    'TSV Schwabmünchen',
    'TuS 1860 Pfarrkirchen',
    'TuS Aschaffenburg-Leider',
    'TuS Geretsried',
    'TuS Holzkirchen',
    'VfB Eichstätt',
    'VfR Garching',
    'Viktoria Aschaffenburg',
    'Wacker Burghausen',
    'Wiggensbach/Buchenberg',
    'Würzburger FV',
  ];

  static List<String> sportOptions = [
    'Keine Auswahl',
    'Fußball',
    'Tennis',
    'Leichtathletik',
    'Handball',
    'Basketball',
    'Volleyball',
    'Eishockey',
    'Tischtennis',
    'Badminton',
    'Reitsport',
    'Schwimmen',
    'Radsport',
    'Golf',
    'Rugby',
    'Boxen',
    'Wassersport',
    'Fechten',
    'Turnen',
    'Rudern',
    'Judo',
    'Ski',
    'Klettern',
    'Billard',
    'Bowling',
  ];
}

List<String> conditions = DropdownOptions.conditionOptions;
List<String> types = DropdownOptions.typeOptions;
Map<String, List<String>> sizesCloth = DropdownOptions.sizeOptionsCloth;
Map<String, List<String>> sizesShoe = DropdownOptions.sizeOptionsShoe;
List<String> popularBrands = DropdownOptions.popularBrandOptions;
List<String> lesspopularBrands = DropdownOptions.lessPopularBrandOptions;
List<String> club = DropdownOptions.clubOptions;
List<String> sport = DropdownOptions.sportOptions;
